In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
array = np.random.randint(1,100,size=(3,4))
array

array([[65, 90, 16, 34],
       [44, 19, 29, 54],
       [ 1, 88, 66,  9]])

In [3]:
np.mean(array,axis=1)

array([51.25, 36.5 , 41.  ])

In [4]:
array.std(axis=1)

array([28.41984342, 13.46291202, 36.93913913])

In [5]:
array.var(axis=1)

array([ 807.6875,  181.25  , 1364.5   ])

In [6]:
B=[56,48,22,41,78,91,24,46,8,33]
a=np.argsort(B)
a

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5], dtype=int64)

In [7]:
m=int(input("Enter first dimension"))
n=int(input("Enter second dimension"))
df = np.random.randint(0,10,size=(m,n))
df

Enter first dimension3
Enter second dimension4


array([[5, 6, 2, 3],
       [7, 5, 0, 5],
       [1, 8, 3, 0]])

In [8]:
df.shape

(3, 4)

In [9]:
df.dtype

dtype('int32')

In [10]:
type(df)

numpy.ndarray

In [11]:

df.reshape(n,m)

array([[5, 6, 2],
       [3, 7, 5],
       [0, 5, 1],
       [8, 3, 0]])

In [12]:
df=np.array([5,8,9,np.nan,3,4,6,0,1,0,1,0,0,np.nan])
zero=np.where(df==0)
zero

(array([ 7,  9, 11, 12], dtype=int64),)

In [13]:
temp=np.nan
non_zero=np.where(df!=0)
non_zero

(array([ 0,  1,  2,  3,  4,  5,  6,  8, 10, 13], dtype=int64),)

In [14]:
nan_val=np.isnan(df)
print(np.where(nan_val==True))

(array([ 3, 13], dtype=int64),)
